### ISSUE TITLE
Tidal resolver doesn't work

### ISSUE THREAD

**Issue by theli-ua** [tomahawk-player/tomahawk-resolvers#101]
Fails on the line https://github.com/tomahawk-player/tomahawk-resolvers/blob/master/tidal/content/contents/code/tidal.js#L92
because TomahawkResolverCapability.UrlLookup is not defined?

**Comment by dschmidt** [comment]
Yeah, those capabilities aren't a thing anymore. You need to create a UrlLookup plugin. 

I will port it myself or post you an example of how to do that.

**Comment by UglyBob79** [comment]
Doesn't work for me either...

**Comment by dschmidt** [comment]
You can comment out that line, until it's properly fixed.

**Comment by willstott101** [comment]
Fixed by https://github.com/tomahawk-player/tomahawk-resolvers/commit/1f0ff78442a00effdbf1efc2402fc269994f0661 ?

**Comment by dschmidt** [comment]
Thanks for confirmation.
