### ISSUE TITLE
Spotify API has been deprecated

### ISSUE THREAD

**Issue by jnylen** [tomahawk-player/tomahawk-resolvers#106]
Migration guide:
https://developer.spotify.com/web-api/migration-guide/

**Comment by dschmidt** [comment]
What are you referring to?

**Comment by jnylen** [comment]
When you drag a song into the program and it starts searching a song. Such as importing songs from Spotify to Tomahawk.

Not only me: tomahawk-player/tomahawk#470

> Error in network request to Spotify for track decoding: "Error downloading http://ws.spotify.com/lookup/1/.json?uri=spotify:track:7BfQtUagX8OMgYSKotIV5Q - server replied: Gone

**Comment by jnylen** [comment]
This line is also using the removed API:
https://github.com/tomahawk-player/tomahawk-resolvers/blob/master/spotify/content/contents/code/spotify.js#L277

**Comment by muesli** [comment]
Thanks for digging this up!

**Comment by mrmaffen** [comment]
fixed: https://github.com/tomahawk-player/tomahawk-resolvers/commit/ff5927d3ba9132816287e6337d92d058d7185bb8 and https://github.com/tomahawk-player/tomahawk-resolvers/commit/d8ae038244651c750e32dad88be193275c9e1a2a
