### ISSUE TITLE
YouTube resolver broken

### ISSUE THREAD

**Issue by rotzbouw** [tomahawk-player/tomahawk-resolvers#114]
E.g. track http://toma.hk/open/track/?artist=Babyfather&title=Meditation is resolved but its URL seems to be a huge string of HTML code.

**Comment by theli-ua** [comment]
Works just fine for me

**Comment by muesli** [comment]
Seems to be working here again, too. Closing for now.

**Comment by rotzbouw** [comment]
Still broken for me. Maybe a localisation issue of some kind. Will debug sometime next week.

**Comment by theli-ua** [comment]
Still works for me
And it would be nice of you to provide some logs when reporting bugs

**Comment by theli-ua** [comment]
There was a bug in tomahawk (not resolver) that was preventing youtube from working correctly (as well as some other resolvers). Try with with latest master, if still doesn't work reopen with more info

**Comment by muesli** [comment]
I don't think that's the case here, though. The resolver also broke on Hatchet and when it started working again, it did both on Tomahawk & Hatchet, too.

**Comment by theli-ua** [comment]
@muesli in that case I'd love to take a look at this assuming there is more info on what platform does this happen on, on what tracks with what results and logs of course.
