### ISSUE TITLE
amazon music resolver stoped working

### ISSUE THREAD

**Issue by Zergie** [tomahawk-player/tomahawk-resolvers#124]
The amazon music resolver does not work anymore. :(
I always get "Username or password incorrect", but it is correct.

![screenshot](https://cloud.githubusercontent.com/assets/9965972/17731571/1a2332e4-646e-11e6-84a4-979cbc65d9ef.png)
[log.txt](https://github.com/tomahawk-player/tomahawk-resolvers/files/422194/log.txt)

**Comment by jpr0930** [comment]
Similar issue. First I get "Invalid Credentials" with this in the logs (credentials redacted): 

> Mon Oct 31 2016 - 08:01:30 [8]: virtual void Tomahawk::JSAccount::startJob(Tomahawk::ScriptJob*) "Tomahawk.PluginManager.invoke('1','0','_testConfig',JSON.parse('{ "email" : "XXXXX@gmail.com", "password" : "XXXXXX", "region" : 0 }'));" 
> Mon Oct 31 2016 - 08:01:30 [0]: JAVASCRIPT: "/home/jason/.local/share/Tomahawk/manualresolvers/amazon/content/contents/code/amazon.js" : "Function not found: _testConfig" 
> Mon Oct 31 2016 - 08:01:30 [0]: void Tomahawk::Accounts::ResolverAccount::onTestConfig(const QVariantMap&) QMap() 
> Mon Oct 31 2016 - 08:01:30 [0]: void DelegateConfigWrapper::onConfigTestResult(Tomahawk::Accounts::ConfigTestResultType) 0

 


Just to test things, I renamed `testConfig` in amazon.js to `_testConfig`, restart and retry. Get same error, but this in the logs, which indicates it is at least trying to resolve:

> Mon Oct 31 2016 - 08:08:25 [0]: QLayout: Attempting to add QLayout "" to DelegateConfigWrapper "", which already has a layout
> Mon Oct 31 2016 - 08:08:26 [8]: virtual void Tomahawk::JSAccount::startJob(Tomahawk::ScriptJob*) "Tomahawk.PluginManager.invoke('2','0','_testConfig',JSON.parse('{ "email" : "XXXXX@gmail.com", "password" : "XXXXX", "region" : 0 }'));" 
> Mon Oct 31 2016 - 08:08:26 [8]: void NetworkReply::metaDataChanged() Redirected HTTP request to QVariant(QUrl, QUrl("https://www.amazon.com/ap/signin?_encoding=UTF8&accountStatusPolicy=P1&openid.assoc_handle=usflex&openid.claimed_id=http://specs.openid.net/auth/2.0/identifier_select&openid.identity=http://specs.openid.net/auth/2.0/identifier_select&openid.mode=logout&openid.ns=http://specs.openid.net/auth/2.0&openid.ns.pape=http://specs.openid.net/extensions/pape/1.0&openid.pape.max_auth_age=0&openid.return_to=https://www.amazon.com:443/gp/redirect.html?location=https://www.amazon.com/gp/dmusic/cloudplayer/forceSignIn/ref=dm_wcp_sfso&token=661ABEA050EC7ED103349320C53489637F654274&source=standards&pageId=amzn_cpweb&showRmrMe=1") ) 
> Mon Oct 31 2016 - 08:08:26 [8]: void NetworkReply::metaDataChanged() Redirected HTTP request to QVariant(QUrl, QUrl("https://www.amazon.com:443/gp/redirect.html?location=https://www.amazon.com/gp/dmusic/cloudplayer/forceSignIn/ref=dm_wcp_sfso&token=661ABEA050EC7ED103349320C53489637F654274&source=standards&") ) 
> Mon Oct 31 2016 - 08:08:26 [8]: void NetworkReply::metaDataChanged() Redirected HTTP request to QVariant(QUrl, QUrl("https://www.amazon.com/gp/dmusic/cloudplayer/forceSignIn/ref=dm_wcp_sfso") ) 
> Mon Oct 31 2016 - 08:08:26 [8]: void NetworkReply::metaDataChanged() Redirected HTTP request to QVariant(QUrl, QUrl("https://www.amazon.com/ap/signin?_encoding=UTF8&accountStatusPolicy=P1&openid.assoc_handle=usflex&openid.claimed_id=http://specs.openid.net/auth/2.0/identifier_select&openid.identity=http://specs.openid.net/auth/2.0/identifier_select&openid.mode=checkid_setup&openid.ns=http://specs.openid.net/auth/2.0&openid.ns.pape=http://specs.openid.net/extensions/pape/1.0&openid.pape.max_auth_age=0&openid.return_to=https://www.amazon.com:443/gp/redirect.html?ie=UTF8&location=https%3A%2F%2Fwww.amazon.com%2Fgp%2Fdmusic%2Fcloudplayer%2Fweb%3Fref%3Ddm_wcp_af_nr%26ref_%3Ddm_wcp_sfso&source=standards&token=661ABEA050EC7ED103349320C53489637F654274#&pageId=amzn_cpweb&showRmrMe=1") ) 
> Mon Oct 31 2016 - 08:08:26 [8]: void NetworkReply::metaDataChanged() Redirected HTTP request to QVariant(QUrl, QUrl("https://music.amazon.com") ) 
> Mon Oct 31 2016 - 08:08:27 [8]: void NetworkReply::metaDataChanged() Redirected HTTP request to QVariant(QUrl, QUrl("https://www.amazon.com/ap/signin?_encoding=UTF8&accountStatusPolicy=P1&openid.assoc_handle=usflex&openid.claimed_id=http://specs.openid.net/auth/2.0/identifier_select&openid.identity=http://specs.openid.net/auth/2.0/identifier_select&openid.mode=checkid_setup&openid.ns=http://specs.openid.net/auth/2.0&openid.ns.pape=http://specs.openid.net/extensions/pape/1.0&openid.pape.max_auth_age=0&openid.return_to=https://www.amazon.com:443/gp/redirect.html?_encoding=UTF8&location=https%3A%2F%2Fmusic.amazon.com%3Fref%3Ddm_wcp_af_nr&source=standards&token=D0B01884E1D45BAC9679700906535935CB7CC00A#&pageId=amzn_cpweb&showRmrMe=1") ) 
> Mon Oct 31 2016 - 08:08:27 [8]: void NetworkReply::metaDataChanged() Redirected HTTP request to QVariant(QUrl, QUrl("https://www.amazon.com:443/gp/redirect.html?_encoding=UTF8&location=https://music.amazon.com?ref=dm_wcp_af_nr&source=standards&token=D0B01884E1D45BAC9679700906535935CB7CC00A#&") ) 
> Mon Oct 31 2016 - 08:08:27 [8]: void NetworkReply::metaDataChanged() Redirected HTTP request to QVariant(QUrl, QUrl("https://music.amazon.com?ref=dm_wcp_af_nr") ) 
> **Mon Oct 31 2016 - 08:08:27 [0]: JAVASCRIPT: "/home/jason/.local/share/Tomahawk/manualresolvers/amazon/content/contents/code/amazon.js" : "Failed to do nativeAsyncRequest" 
> Mon Oct 31 2016 - 08:08:27 [0]: JAVASCRIPT: "/home/jason/.local/share/Tomahawk/manualresolvers/amazon/content/contents/code/amazon.js" : "Status Code was: 400" 
> Mon Oct 31 2016 - 08:08:27 [0]: void Tomahawk::Accounts::ResolverAccount::onTestConfig(const QVariantMap&) QMap() 
> Mon Oct 31 2016 - 08:08:27 [0]: void DelegateConfigWrapper::onConfigTestResult(Tomahawk::Accounts::ConfigTestResultType) 0**

**Comment by theli-ua** [comment]
Most likely you have an outdated build of tomahawk.
There have been some commits in tomahawk recently without which tomahawk wont work.
Looks like you have nightly from ppa, but I don't think those are even updated anymore

**Comment by jpr0930** [comment]
Welp, you were right. Built from the latest master and Amazon Music works fine. Subsonic is now broken, so on to debugging that. Thanks for the help!
