### ISSUE TITLE
Improve Deezer resolver with Native SDK (for desktops)

### ISSUE THREAD

**Issue by lbssousa** [tomahawk-player/tomahawk-resolvers#127]
Could it be possible to improve Tomahawk resolver for Deezer using its [Native SDK](https://developers.deezer.com/sdk/native)? Does it fit your needs?

**Comment by theli-ua** [comment]
That link requires you to sign up to see contents.
Also I'm not using deezer.
But anyway - whats wrong with current resolver?

**Comment by lbssousa** [comment]
Taken from http://developers.deezer.com/sdk/native (after login):

# DEEZER Native SDK User Guide
## Main features and changes
Stay tuned for new releases by subscribing to the Native SDK’s release feed.

### Network stack
The SDK provides a set of network utilities. These utilities are used internally by the SDK but can be used by your application as well. Please read the corresponding Network Stack section.

### Enhanced player
The DEEZER Player of the Native SDK can play contents such as:
* songs (individually)
* albums
* playlists
* radios (aka mixes)

Please refer to the section dedicated to the DEEZER Player for more details.

The DEEZER Player supports mixes generated from a playlist, an artist, an album or a user. The latter feature is also known as Flow.

### Offline mode and smart cache
The DEEZER Native SDK provides an offline mode which allows your application to download and store albums and playlists locally. The content marked as synchronized offline can then be played without a network connection.

The SDK also provides a smart cache mechanism keeping last played songs on the file system up to the maximum size set by the application. Please read the corresponding Offline Mode section.

**Comment by mrmaffen** [comment]
This issue should be moved here: https://github.com/tomahawk-player/tomahawk/issues
The deezer resolver already supports everything so that the desktop client could in theory prepare tracks by using the Deezer SDK
