### ISSUE TITLE
TIDAL resolver cannot log in

### ISSUE THREAD

**Issue by elgithubo** [tomahawk-player/tomahawk-resolvers#131]
When trying to log in using the tidal resolver configuration dialog, it just states "Unable to authenticate. Please check your connection".
In the shell output I receive:
09:55:29 [0]: JAVASCRIPT: "/home/elgrande/git/tomahawk-resolvers/tidal/content/contents/code/tidal.js" : "Failed to do POST request: to: https://listen.tidal.com/v1/login/username?token=P5Xbeo5LFvESeDy6" 
09:55:29 [0]: JAVASCRIPT: "/home/elgrande/git/tomahawk-resolvers/tidal/content/contents/code/tidal.js" : "Status Code was: 500"

**Comment by Spartinus** [comment]
I had the same exact issue. I honestly couldn't figure it out and gave up-- Hopefully someone can help us with this!

**Comment by theli-ua** [comment]
What tomahawk version are you using? I mean, is this "it was working for me and now it doesn't"  or is it "i never made it to work at all" situation?

**Comment by Spartinus** [comment]
Sorry... I hope you didn't take offense to my post... The Tomahawk version I'm currently using is 0.8.99. I tried the previous stable version offered on the site as well (0.8.4), but I still didn't have any luck. As for the plugins, I have tried all of the latest nightly ones from 0.0.4 --> 0.0.7.

**Comment by theli-ua** [comment]
Where did you get that 0.8.99 from? Is it built from master?

I don't have an active Tidal subscription anymore but I'll see If I can test login at least with my account

**Comment by Spartinus** [comment]
Thanks! The latest Nightly Build (.dmg) on the Github is 0.8.99

**Comment by dschmidt** [comment]
Should be fixed in #136
